### ISSUE TITLE
Submit I-D to IETF tracker

### ISSUE THREAD

**Issue by sgillies** [geojson/draft-geojson#14]
Use the form at http://datatracker.ietf.org/submit/

Checklist (from guidelines at http://www.ietf.org/id-info/guidelines.html):
- [x] [IPR-Related Notices Required in Internet-Drafts](http://www.ietf.org/id-info/guidelines.html#iprnotices)
- [x] [Internet-draft boilerplate](http://www.ietf.org/id-info/guidelines.html#anchor7)
- [x] [Formatting](http://www.ietf.org/id-info/guidelines.html#anchor11)
- [x] [Naming and submission](http://www.ietf.org/id-info/guidelines.html#naming)

Proposed name: draft-butler-geojson-00. Howard Butler is the first author in alphabetical order.

Submission-ready draft.txt: https://gist.github.com/sgillies/8304592.
